
spring:
  application:
    name: empdetailsms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/adv_emp_details
    username: root
    password: root 
  jpa:
    hibernate:
      ddl-auto: none
      format_sql: false
    show-sql: true
#    properties: 
#      hibernate:
#  flyway:
#    baseline-on-migrate: true
#    validate-on-migrate: true
#    baseline-description: init
#    fail-on-missing-locations: true
#    schemas: public
#    enabled: true
#    locations: classpath:db/migration
#    url: jdbc:mysql://localhost:3306/adv_emp_details
#    user: root
#    password: root

server:
  port: 8800
  servlet:
    context-path: /empdetails/employee